In [30]:
import numpy
pressure_data = numpy.load('SLP/danaLab/00001/PMarray/cover1/000001.npy')
print(pressure_data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [27]:
import scipy.io
mat = scipy.io.loadmat('SLP/danaLab/00001/joints_gt_IR.mat')
subject = mat["joints_gt"]
print(subject)
print(subject.shape)

[[[ 44.85588508  44.85588508  62.94670992 ...  72.14040778  72.43697868
    71.84383689]
  [ 47.82159407  47.52502317  35.66218721 ...  45.15245598  46.63531047
    45.15245598]
  [ 53.15987025  54.34615385  51.08387396 ...  64.42956441  62.94670992
    65.91241891]
  ...
  [ 89.93466172  90.23123262  89.34151993 ...  74.51297498  68.8781279
    62.35356812]
  [ 64.13299351  65.02270621  64.42956441 ...  56.71872104  55.82900834
    57.01529194]
  [ 63.83642261  64.13299351  62.94670992 ...  45.15245598  45.44902688
    48.71130677]]

 [[131.65848007 131.36190918 111.78822984 ... 110.60194625 110.00880445
   108.22937905]
  [104.37395737 108.22937905  99.62882298 ...  99.33225209  97.55282669
    98.44253939]
  [ 80.35171455  80.94485635  77.38600556 ...  83.02085264  78.86886006
    75.60658017]
  ...
  [ 72.93744208  72.64087118  71.15801668 ...  75.60658017  80.35171455
    18.07182576]
  [ 28.74837813  28.45180723  29.04494903 ...  31.71408712  32.01065802
    30.23123262]
  [ 10.0